import 'package:json_annotation/json_annotation.dart';

import 'mesaj_kimler.dart';
part 'mesaj_model.g.dart';
///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///

@JsonSerializable()
class TestMesaj {
/*
{
  "basliq": "Ut problem",
  "gonderen": "Ulvi Nebiyev",
  "kimler": [
    {
      "ad": "Turxna Ibrahimov"
    }
  ],
  "qebulEtdi": "Elgiz Cebrayilov",
  "tarix": "2021-05-25 16:45:15",
  "timer": "2021-9-12 17:27:14",
  "timerStatus": 0,
  "mesajStatus": 1
} 
*/

  int? id;
  String? basliq;
  String? gonderen;
  List<TestMesajKimler?>? kimler;
  String? qebulEtdi;
  String? tarix;
  String? timer;
  int? timerStatus;
  int? mesajStatus;

  TestMesaj({
    this.id,
    this.basliq,
    this.gonderen,
    this.kimler,
    this.qebulEtdi,
    this.tarix,
    this.timer,
    this.timerStatus,
    this.mesajStatus,
  });
factory  TestMesaj.fromJson(Map<String, dynamic> json) =>_$TestMesajFromJson(json);
  Map<String, dynamic> toJson() =>_$TestMesajToJson(this);
}
