import 'package:json_annotation/json_annotation.dart';
part "mesaj_model.g.dart";

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
const String jsonKeyMesajModelText = 'text';


@JsonSerializable()
class MesajModel {
/*
{
  "text": "Bazaya əlavə edildi."
} 
*/

  String? text;

  MesajModel({
    this.text,
  });
  factory MesajModel.fromJson(Map<String, dynamic> json)=> _$MesajModelFromJson(json);
  Map<String, dynamic> toJson() =>_$MesajModelToJson(this);
}